#!/usr/bin/env sh
while read file
do
        case "$1" in
        "w") setbg "$file" & ;;
        "c")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/bmdirs | awk '{print $2}' | rofi -m -1 -sidebar-mode -location 2 -dmenu -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
        "m")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/.config/bmdirs | awk '{print $2}' | rofi -m -1 -sidebar-mode -location 2 -dmenu -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | rofi -m -1 -sidebar-mode -location 2 -dmenu -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	"g")	ifinstalled gimp && gimp "$file" & ;;
        esac
done
