#!/usr/bin/env sh
alias ka="killall" \
  mkd="mkdir -pv" \
  mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
  calcurse="calcurse -D ~/.config/calcurse" \
  magit="nvim -c MagitOnly" \
  p="sudo pacman" \
  SS="sudo systemctl" \
  f="$FILE" \
  g="git" \
  trem="transmission-remote" \
  e="$EDITOR" \
  v="$EDITOR" \
  x="sxiv -ft *" \
  sdn="sudo shutdown -h now" \
  gua="git remote | xargs -L1 git push --all" \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="grep --color=auto" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
  yta="yt -x -f bestaudio/best" \
  YT="youtube-viewer" \
  ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
  upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
  lsp="pacman -Qett --color=always | less" \
  ffmpeg="ffmpeg -hide_banner" \
  y="yarn" \
  vw="nvim -u ~/.config/nvim/wiki-init.vim -c VimwikiIndex" \
  ll='ls -lAFh --group-directories-first' \
  llt='ls -lAFht --group-directories-first' \
  d='docker' \
  b='bat' \

  if [ -n "$ZSH_VERSION" ]; then
    alias -g J='| python -m json.tool'
    alias -g X='| xsel -bi'
    alias -g B='| /usr/bin/bat --style="plain"'
    alias -g L='| /usr/bin/less'
  elif [ -n "$BASH_VERSION" ]; then
    _xfunc git __git_complete g _git
    complete -F _yarn y
  fi

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}

# terminal-scheme dark|light
function terminal-scheme() {
  nvim_config_file=~/.config/nvim/init.vim
  sed -i "s/\(^set background=\).*/\1$1/g" $nvim_config_file
  wiki_config_file=~/.config/nvim/wiki-init.vim
  sed -i "s/\(^set background=\).*/\1$1/g" $wiki_config_file
  # bat_config_file=~/dotfiles/bat/config
  # if [[ $1 == 'light' ]]; then
  #   echo '--theme="OneHalfLight"' > $bat_config_file
  # else
  #   echo '--theme="OneHalfDark"' > $bat_config_file
  # fi
  kitty_config_file=~/.config/kitty/kitty.conf
  sed -i "s#^\(include\s\./kitty-themes/gruvbox_*\).*#\1$1.conf#g" $kitty_config_file
  kitty @ set-colors --all --configured  ~/.config/kitty/kitty-themes/gruvbox_$1.conf
  rofi_config_file=~/.config/rofi/config
  sed -i "s#^\(rofi.theme: /usr/share/rofi/themes/gruvbox-*\).*#\1$1-soft.rasi#g" $rofi_config_file
}
