#!/usr/bin/env sh

# yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \

alias ka="killall" \
  SS="sudo systemctl" \
  YT="youtube-viewer" \
  b='bat' \
  c='clear' \
  calcurse="calcurse -D ~/.config/calcurse" \
  ccat="highlight --out-format=ansi" \
  d='docker' \
  diff="diff --color=auto" \
  e="$EDITOR" \
  f="$FILE" \
  ffmpeg="ffmpeg -hide_banner" \
  g="git" \
  glg="git log --graph --date-order --date=format-local:'%F %R' --full-history --color --decorate --pretty=format:'%x08%x09%C(red)%h %C(cyan)%ad %C(bold blue)%aN%C(reset)%C(bold yellow)%d %C(reset)%s'" \
  glga="git log --graph --date-order --date=format-local:'%F %R' --full-history --all --color --decorate --pretty=format:'%x08%x09%C(red)%h %C(cyan)%ad %C(bold blue)%aN%C(reset)%C(bold yellow)%d %C(reset)%s'" \
  grep="grep --color=auto" \
  gua="git remote | xargs -L1 git push --all" \
  gss="git status -sb" \
  icat="kitty +kitten icat" \
  ll='ls -lAFh --group-directories-first' \
  llt='ls -lAFht --group-directories-first' \
  ls="ls -hN --color=auto --group-directories-first" \
  lsp="pacman -Qett --color=always | less" \
  magit="nvim -c MagitOnly" \
  mkd="mkdir -pv" \
  mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
  p="sudo pacman" \
  ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
  sdn="sudo shutdown -h now" \
  trem="transmission-remote" \
  upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
  v="$EDITOR" \
  vw="nvim -u ~/.config/nvim/wiki-init.vim -c VimwikiIndex" \
  x="sxiv -ft *" \
  y="yarn" \
  yl="yarn lint" \
  ytw="yarn test --watch" \
  yta="yt -x -f bestaudio/best"

if [ -n "$ZSH_VERSION" ]; then
  alias -g J='| python -m json.tool'
  alias -g X='| xsel -bi'
  alias -g B='| /usr/bin/bat --style="plain"'
  alias -g L='| /usr/bin/less'
  alias -g F='| fx'
  alias -g N='&& dunstify "done"'
elif [ -n "$BASH_VERSION" ]; then
  _xfunc git __git_complete g _git
  complete -F _yarn y
fi

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}

# terminal-scheme dark|light
function terminal-scheme() {
  nvim_config_file=~/.config/nvim/init.vim
  sed -i "s/\(^set background=\).*/\1$1/g" $nvim_config_file
  wiki_config_file=~/.config/nvim/wiki-init.vim
  sed -i "s/\(^set background=\).*/\1$1/g" $wiki_config_file
  # bat_config_file=~/.config/bat/config
  # if [[ $1 == 'light' ]]; then
  #   echo '--theme="OneHalfLight"' > $bat_config_file
  # else
  #   echo '--theme="OneHalfDark"' > $bat_config_file
  # fi
  kitty_config_file=~/.config/kitty/kitty.conf
  sed -i "s#^\(include\s\./kitty-themes/gruvbox_*\).*#\1$1.conf#g" $kitty_config_file
  kitty @ set-colors --all --configured  ~/.config/kitty/kitty-themes/gruvbox_$1.conf
  rofi_config_file=~/.config/rofi/config
  sed -i "s#^\(rofi.theme: /usr/share/rofi/themes/gruvbox-*\).*#\1$1-soft.rasi#g" $rofi_config_file
  qute_config_file=~/.config/qutebrowser/config.py
  if [[ $1 == 'light' ]]; then
    sed -i "s#^\(c\.content\.user_stylesheets = \).*#\1[]#" $qute_config_file
    sed -i "s#^\(c\.colors\.webpage\.bg = \).*#\1'white'#" $qute_config_file
  else
    sed -i "s#^\(c\.content\.user_stylesheets = \).*#\1'~/.config/qutebrowser/dark2.css'#" $qute_config_file
    sed -i "s#^\(c\.colors\.webpage\.bg = \).*#\1'black'#" $qute_config_file
  fi
  if xwininfo -tree -root | grep ' ("qutebrowser" ' > /dev/null 2>&1; then
    if [[ $1 == 'light' ]]; then
      qutebrowser ':set --temp content.user_stylesheets [] ;; set --temp colors.webpage.bg "white"' > /dev/null 2>&1
    else
      qutebrowser ':set --temp content.user_stylesheets "~/.config/qutebrowser/dark2.css" ;; set --temp colors.webpage.bg "black"' > /dev/null 2>&1
    fi
  fi
  zathura_config_file=~/.config/zathura/zathurarc
  if [[ $1 == 'light' ]]; then
    sed -i "s/\(^set recolor \).*/\1false/g" $zathura_config_file
  else
    sed -i "s/\(^set recolor \).*/\1true/g" $zathura_config_file
  fi
  vifm_config_file=~/.config/vifm/vifmrc
  sed -i "s#^\(colorscheme\s\).*#\1$1#g" $vifm_config_file
  xresources_config_file=~/.Xresources
  sed -i "s#^\(\#include \".config/xterm/*\).*#\1$1\"#g" $xresources_config_file
  xrdb -merge ~/.Xresources
  for i in $( nvr --serverlist ); do
    if [[ $1 == 'light' ]]; then
      nvr --servername $i  --remote-send '<c-\><c-n>;set background=light<cr>'
    else
      nvr --servername $i  --remote-send '<c-\><c-n>;set background=dark<cr>'
    fi
  done
}

# Change background color of current (and child) kitty instance.
function kbg() {
  kitty @ set-colors --all --configured  ~/.config/kitty/kitty-themes/gruvbox_$1.conf
}
